# Generated by Django 6.0 on 2025-12-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_contactmessage_rating_alter_contactmessage_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
