# Generated by Django 6.0 on 2025-12-27 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_contactmessage_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={},
        ),
    ]
